# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

N = 4000000


def fibo(limit=-1):
    n_2 = 1
    yield n_2

    n_1 = 1
    yield n_1

    while True:
        n_2, n_1 = n_1, n_1 + n_2
        if n_1 > limit > 0:
            return
        yield n_1


def even_fibos(N):
    return (f for f in fibo(N) if f % 2 == 0)


print("even fibos\t\t", list(even_fibos(N)))

result = sum(even_fibos(N))
print("sum even fibos\t", result)

